### ISSUE TITLE
Docker read only system error

### ISSUE THREAD

**Issue by Futureganteng** [dmblock/LiteLoaderBDS-docker#1]
=> => transferring context: 389B                                          0.1s
 => ERROR [ 2/14] RUN mv /etc/apt/sources.list /etc/apt/sources.bak        1.8s
------
 > [ 2/14] RUN mv /etc/apt/sources.list /etc/apt/sources.bak         && echo 'nameserver 8.8.8.8' >> /etc/resolv.conf         && echo 'nameserver 223.5.5.5' >> /etc/resolv.conf:
#0 1.722 /bin/sh: 1: cannot create /etc/resolv.conf: Read-only file system
------
Dockerfile:7

i have an error on building image, and ya on MCSManager Panel seem like have a error too
Os: Ubuntu 22.04.2 LTS

**Comment by dmblock** [comment]
try to delete the line from 'echo nameserver....' to '.../etc/resolv.conf' 
if U are not living in China,delete the line in 'COPY etc/apt sources.list /etc/apt/sources.list'
save and then try again

在 2023-02-24 19:42:00，Future ***@***.***> 写道：


=> => transferring context: 389B 0.1s
=> ERROR [ 2/14] RUN mv /etc/apt/sources.list /etc/apt/sources.bak 1.8s

[ 2/14] RUN mv /etc/apt/sources.list /etc/apt/sources.bak && echo 'nameserver 8.8.8.8' >> /etc/resolv.conf && echo 'nameserver 223.5.5.5' >> /etc/resolv.conf:
#0 1.722 /bin/sh: 1: cannot create /etc/resolv.conf: Read-only file system

Dockerfile:7

i have an error on building image, and ya on MCSManager Panel seem like have a error too
Os: Ubuntu 22.04.2 LTS
